# numpy

In [1]:
import numpy as np

In [2]:
#check version of the numpy library
import numpy as np
np.__version__

'1.21.5'

In [5]:
#create a numpy array
a=np.array([1,4,2,5,3])
print(a.dtype)
a

int32


array([1, 4, 2, 5, 3])

In [11]:
[1,'2',3,4,False]

[1, '2', 3, 4, False]

In [13]:
import numpy as np
np.array([1,'2',3,4,False])

TypeError: 'list' object is not callable

In [4]:
#create a sample list
sample_list=([1,2,3,4])

In [5]:
sample_list*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
#create a sample numpy array
sample_numpy_array = np.array([1,2,3,4,5])

In [8]:
sample_numpy_array*2

array([ 2,  4,  6,  8, 10])

In [4]:
#create matrix using numpy
a =[[1,2,3],
   [4,5,6],
   [7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
a = np.array(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(a[0])
print(a[0][1])
print(a[2][2])

[1 2 3]
2
9


In [14]:
b = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
import numpy as np
([1,2,3,4],
[5,6,7,8])

([1, 2, 3, 4], [5, 6, 7, 8])

In [ ]:
import numpy as np
np.list([1,2,3],
       [4,5,6],
       [7,8,9])

In [9]:
import numpy as np
import random
np.random.randint(0,10,(3,3))

array([[0, 1, 3],
       [1, 1, 7],
       [7, 8, 0]])

In [7]:
import numpy as np
np.zeros((3,3),dtype = 'int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
import numpy as np
np.ones((3,3),dtype = 'int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
import numpy as np
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [14]:
import numpy as np
import random
np.random.randint(0,10,(3,4))

array([[9, 6, 9, 9],
       [8, 3, 4, 5],
       [3, 5, 5, 7]])

In [15]:
import numpy as np
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [16]:
#fixing the random seed
print(np.random.seed(10))
np.random.randint(0,10,(3,3))

None


array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9]])

In [22]:
#fixing the random seed
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [23]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# array concatenation

In [16]:
#cincatenating 2-D arrays
matrix1 = np.array([[1,2,3],
                   [4,5,6]])
print("matrix1")
matrix1

matrix1


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
matrix2 = np.array([[7,8,9],
                   [10,11,12]])

matrix2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [19]:
#concatenate along the first axis
matrix_1_2_combineRowwise = np.concatenate([matrix1,matrix2],axis = 0)
print("combined on Row (axis = 0)")
matrix_1_2_combineRowwise

combined on Row (axis = 0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
#concatenate along the second axis(zero-indexed)
matrix1_2_combineColwise = np.concatenate([matrix1,matrix2],axis=1)
print("combined on col (axis=1)")
matrix1_2_combineColwise

combined on col (axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# work

In [21]:
m1 = np.array([[1,2,3],
      [4,5,6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
m2 = np.array([[7,8,9],
              [10,11,12]])
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [23]:
m3 = np.concatenate([m1,m2],axis = 0)
m3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
import numpy as np
import random
a = np.random.randint(0,10,(4,2))
a
a.shape
np.identity(4,dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [35]:
import numpy as np
import random 
np.random.seed(10)
np.random.randint(100,200,(5,2))

array([[109, 115],
       [164, 128],
       [189, 193],
       [129, 108],
       [173, 100]])

In [38]:
import numpy as np
import random
np.random.randint(10,30,(1,6))

array([[14, 29, 26, 14, 25, 21]])

In [39]:
import numpy as np
import random
np.random.randint(10,30,(2,3,4))

array([[[21, 11, 18, 14],
        [24, 27, 29, 23],
        [15, 23, 29, 23]],

       [[22, 11, 14, 28],
        [23, 21, 20, 19],
        [25, 28, 26, 17]]])

In [40]:
import numpy as np
import random
np.random.randint(10,30,(3,3))

array([[21, 27, 24],
       [17, 21, 11],
       [10, 22, 15]])

In [42]:
import numpy as np
import random
np.random.randint(0,11,(3,3))

array([[ 6,  6,  5],
       [10,  6,  0],
       [ 0,  6,  9]])

In [54]:
import numpy as np
import random
a=np.random.randint(0,10,(3,3))
print(a)
print(a.min())
print(a.max())

[[7 6 5]
 [8 2 2]
 [0 1 2]]
0
8


In [18]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [10]:
from numpy import *
arr = logspace(1,20,5)
print(arr)

[1.00000000e+01 5.62341325e+05 3.16227766e+10 1.77827941e+15
 1.00000000e+20]


In [12]:
from numpy import *
arr = arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [13]:
from numpy import *
arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [17]:
from numpy import *
arr = zeros(5,int)
print(arr)

[0 0 0 0 0]


In [16]:
from numpy import *
arr = ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [15]:
from numpy import *
arr = ones(5,int)
print(arr)

[1 1 1 1 1]


In [2]:
   np.__version__                            

'1.21.5'

In [9]:
import numpy as np
np.array([1,2,3,'a'])

TypeError: 'list' object is not callable